name = "planocerto"
compatibility_date = "2025-01-08"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist/client"

[build]
command = "yarn install && yarn build"

[build.upload]
format = "service-worker"
