/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecomendarRouteImport } from './routes/recomendar'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentCancelRouteImport } from './routes/payment-cancel'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GlossarioRouteImport } from './routes/glossario'
import { Route as FiltrosSalvosRouteImport } from './routes/filtros-salvos'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as CoberturaRouteImport } from './routes/cobertura'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanoPlanIdRouteImport } from './routes/plano.$planId'
import { Route as BlogPostIdRouteImport } from './routes/blog.$postId'
import { Route as AdminCommissionsRouteImport } from './routes/admin/commissions'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecomendarRoute = RecomendarRouteImport.update({
  id: '/recomendar',
  path: '/recomendar',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment-cancel',
  path: '/payment-cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioRoute = GlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const FiltrosSalvosRoute = FiltrosSalvosRouteImport.update({
  id: '/filtros-salvos',
  path: '/filtros-salvos',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaRoute = CoberturaRouteImport.update({
  id: '/cobertura',
  path: '/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoPlanIdRoute = PlanoPlanIdRouteImport.update({
  id: '/plano/$planId',
  path: '/plano/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdRoute = BlogPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => BlogRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/admin/commissions',
  path: '/admin/commissions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/blog': typeof BlogRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/calculadora': typeof CalculadoraRoute
  '/cobertura': typeof CoberturaRoute
  '/comparar': typeof CompararRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/favoritos': typeof FavoritosRoute
  '/filtros-salvos': typeof FiltrosSalvosRoute
  '/glossario': typeof GlossarioRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/payment-cancel': typeof PaymentCancelRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/premium': typeof PremiumRoute
  '/recomendar': typeof RecomendarRoute
  '/signup': typeof SignupRoute
  '/simulador': typeof SimuladorRoute
  '/sobre': typeof SobreRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/plano/$planId': typeof PlanoPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/blog': typeof BlogRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/calculadora': typeof CalculadoraRoute
  '/cobertura': typeof CoberturaRoute
  '/comparar': typeof CompararRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/favoritos': typeof FavoritosRoute
  '/filtros-salvos': typeof FiltrosSalvosRoute
  '/glossario': typeof GlossarioRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/payment-cancel': typeof PaymentCancelRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/premium': typeof PremiumRoute
  '/recomendar': typeof RecomendarRoute
  '/signup': typeof SignupRoute
  '/simulador': typeof SimuladorRoute
  '/sobre': typeof SobreRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/plano/$planId': typeof PlanoPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/blog': typeof BlogRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/calculadora': typeof CalculadoraRoute
  '/cobertura': typeof CoberturaRoute
  '/comparar': typeof CompararRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/favoritos': typeof FavoritosRoute
  '/filtros-salvos': typeof FiltrosSalvosRoute
  '/glossario': typeof GlossarioRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/payment-cancel': typeof PaymentCancelRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/premium': typeof PremiumRoute
  '/recomendar': typeof RecomendarRoute
  '/signup': typeof SignupRoute
  '/simulador': typeof SimuladorRoute
  '/sobre': typeof SobreRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/plano/$planId': typeof PlanoPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/blog'
    | '/buscar'
    | '/calculadora'
    | '/cobertura'
    | '/comparar'
    | '/configuracoes'
    | '/dashboard'
    | '/faq'
    | '/favoritos'
    | '/filtros-salvos'
    | '/glossario'
    | '/login'
    | '/newsletter'
    | '/payment-cancel'
    | '/payment-success'
    | '/premium'
    | '/recomendar'
    | '/signup'
    | '/simulador'
    | '/sobre'
    | '/admin/commissions'
    | '/blog/$postId'
    | '/plano/$planId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/blog'
    | '/buscar'
    | '/calculadora'
    | '/cobertura'
    | '/comparar'
    | '/configuracoes'
    | '/dashboard'
    | '/faq'
    | '/favoritos'
    | '/filtros-salvos'
    | '/glossario'
    | '/login'
    | '/newsletter'
    | '/payment-cancel'
    | '/payment-success'
    | '/premium'
    | '/recomendar'
    | '/signup'
    | '/simulador'
    | '/sobre'
    | '/admin/commissions'
    | '/blog/$postId'
    | '/plano/$planId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/blog'
    | '/buscar'
    | '/calculadora'
    | '/cobertura'
    | '/comparar'
    | '/configuracoes'
    | '/dashboard'
    | '/faq'
    | '/favoritos'
    | '/filtros-salvos'
    | '/glossario'
    | '/login'
    | '/newsletter'
    | '/payment-cancel'
    | '/payment-success'
    | '/premium'
    | '/recomendar'
    | '/signup'
    | '/simulador'
    | '/sobre'
    | '/admin/commissions'
    | '/blog/$postId'
    | '/plano/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BlogRoute: typeof BlogRouteWithChildren
  BuscarRoute: typeof BuscarRoute
  CalculadoraRoute: typeof CalculadoraRoute
  CoberturaRoute: typeof CoberturaRoute
  CompararRoute: typeof CompararRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  FavoritosRoute: typeof FavoritosRoute
  FiltrosSalvosRoute: typeof FiltrosSalvosRoute
  GlossarioRoute: typeof GlossarioRoute
  LoginRoute: typeof LoginRoute
  NewsletterRoute: typeof NewsletterRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PremiumRoute: typeof PremiumRoute
  RecomendarRoute: typeof RecomendarRoute
  SignupRoute: typeof SignupRoute
  SimuladorRoute: typeof SimuladorRoute
  SobreRoute: typeof SobreRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  PlanoPlanIdRoute: typeof PlanoPlanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recomendar': {
      id: '/recomendar'
      path: '/recomendar'
      fullPath: '/recomendar'
      preLoaderRoute: typeof RecomendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-cancel': {
      id: '/payment-cancel'
      path: '/payment-cancel'
      fullPath: '/payment-cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario': {
      id: '/glossario'
      path: '/glossario'
      fullPath: '/glossario'
      preLoaderRoute: typeof GlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filtros-salvos': {
      id: '/filtros-salvos'
      path: '/filtros-salvos'
      fullPath: '/filtros-salvos'
      preLoaderRoute: typeof FiltrosSalvosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura': {
      id: '/cobertura'
      path: '/cobertura'
      fullPath: '/cobertura'
      preLoaderRoute: typeof CoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano/$planId': {
      id: '/plano/$planId'
      path: '/plano/$planId'
      fullPath: '/plano/$planId'
      preLoaderRoute: typeof PlanoPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$postId': {
      id: '/blog/$postId'
      path: '/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/admin/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogPostIdRoute: typeof BlogPostIdRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogPostIdRoute: BlogPostIdRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BlogRoute: BlogRouteWithChildren,
  BuscarRoute: BuscarRoute,
  CalculadoraRoute: CalculadoraRoute,
  CoberturaRoute: CoberturaRoute,
  CompararRoute: CompararRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  FavoritosRoute: FavoritosRoute,
  FiltrosSalvosRoute: FiltrosSalvosRoute,
  GlossarioRoute: GlossarioRoute,
  LoginRoute: LoginRoute,
  NewsletterRoute: NewsletterRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PremiumRoute: PremiumRoute,
  RecomendarRoute: RecomendarRoute,
  SignupRoute: SignupRoute,
  SimuladorRoute: SimuladorRoute,
  SobreRoute: SobreRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  PlanoPlanIdRoute: PlanoPlanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
